# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desing1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

class Ui_MainWindow(object):

    #Styles

    StyleLineEditOk = ("QLineEdit{\n"
"    border: 2px solid rgb(45,45,45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255,207,0);\n"
"}")

    StyleLineEditErro = ("QLineEdit{\n"
"    border: 2px solid rgb(255, 85, 127);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255,207,0);\n"
"}")

    frameErroRed = ("background-color: rgb(255, 85, 127);")
    frameErroGreen = ("background-color: rgb(0, 255, 123);")
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 499)
        MainWindow.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_erro = QtWidgets.QFrame(self.top_bar)
        self.frame_erro.setMaximumSize(QtCore.QSize(250, 16777215))
        
        self.frame_erro.setStyleSheet(self.frameErroRed)
        
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_erro = QtWidgets.QLabel(self.frame_erro)
        self.label_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_3.addWidget(self.label_erro)
        self.botao_x = QtWidgets.QPushButton(self.frame_erro)
        self.botao_x.setMaximumSize(QtCore.QSize(20, 20))
        self.botao_x.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 74, 74);\n"
"}")
        self.botao_x.setObjectName("botao_x")
        self.horizontalLayout_3.addWidget(self.botao_x)
        self.horizontalLayout_2.addWidget(self.frame_erro)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.login_area.setFont(font)
        self.login_area.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"border-radius:10px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.Funcionario = QtWidgets.QLineEdit(self.login_area)
        self.Funcionario.setGeometry(QtCore.QRect(30, 60, 200, 51))
        
        self.Funcionario.setStyleSheet(self.StyleLineEditOk)
        
        self.Funcionario.setObjectName("Funcionario")
        self.Atividade = QtWidgets.QLineEdit(self.login_area)
        self.Atividade.setGeometry(QtCore.QRect(30, 130, 200, 51))
        
        self.Atividade.setStyleSheet(self.StyleLineEditOk)
        
        self.Atividade.setObjectName("Atividade")
        self.Entrar = QtWidgets.QPushButton(self.login_area)
        self.Entrar.setGeometry(QtCore.QRect(30, 200, 200, 30))
        self.Entrar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(20,20,20);\n"
"    border: 2px solid rgb(60,60,60);\n"
"    color: rgb(200, 200, 200);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(60,60,60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(250,230,0);\n"
"    border: 2px solid rgb(255,165,24);\n"
"    color: rgb(35,35,35);\n"
"}")
        self.Entrar.setObjectName("Entrar")
        self.label = QtWidgets.QLabel(self.login_area)
        self.label.setGeometry(QtCore.QRect(40, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,207,0);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        #Fechar popup
        self.botao_x.clicked.connect(lambda: self.frame_erro.hide())

        #Esconder erro
        self.frame_erro.hide()

        #Login
        self.Entrar.clicked.connect(self.checkFields)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Atividade"))
        self.label_erro.setText(_translate("MainWindow", "Atividade Atualizada"))
        self.botao_x.setText(_translate("MainWindow", "X"))
        self.Funcionario.setPlaceholderText(_translate("MainWindow", "Funcionário"))
        self.Atividade.setPlaceholderText(_translate("MainWindow", "Atividade"))
        self.Entrar.setText(_translate("MainWindow", "SUBMIT"))
        self.label.setText(_translate("MainWindow", "Atualização de Atividade"))


    def checkFields(self):
        textUser = ""
        textPassword = ""

        def showMessage(message):
            self.frame_erro.show()
            self.label_erro.setText(message)

        if not self.Funcionario.text():
            textUser = "Funcionário Vazio. "
            self.Funcionario.setStyleSheet(self.StyleLineEditErro)
            
        else:
            textUser = ""
            self.Funcionario.setStyleSheet(self.StyleLineEditOk)

        if not self.Atividade.text():
            textPassword = "Atividade Vazio."
            self.Atividade.setStyleSheet(self.StyleLineEditErro)
        else:
            textPassword = ""
            self.Atividade.setStyleSheet(self.StyleLineEditOk)

        if ((textUser != "") or (textPassword != "")):
            texto = textUser + textPassword
            r = "1"
            ts(s,r)
            showMessage(texto)
            self.frame_erro.setStyleSheet(self.frameErroRed)
            
        else:
            nome = self.Funcionario.text()
            nomecom =""
            word = nome.split()
            if len(word) == 1:
                nomecom = str(nome)
            if len(word) > 1:
                for i in range(len(word)-1):
                    nomecom = nomecom+str(word[i])+"_"
                nomecom = nomecom+str(word[len(word)-1])
            atividade = self.Atividade.text()
            tempo = datetime.datetime.now()
            tempo = str(tempo)
            tempo = tempo[11:19]
            atividadecom =""
            palavra = atividade.split()
            if len(palavra) == 1:
                atividadecom = str(atividade)
            if len(palavra) > 1:
                for i in range(len(palavra)-1):
                    atividadecom = atividadecom+str(palavra[i])+"_"
                atividadecom = atividadecom+str(palavra[len(palavra)-1])
            r = str(nomecom+"\t"+atividadecom+"\t"+str(tempo))
            ts(s,r)
            showMessage("Atividade Atualizada")
            self.frame_erro.setStyleSheet(self.frameErroGreen)

        
    


if __name__ == "__main__":
    import sys
    import socket
    
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host ="Colocar ip do servidor aqui"
    port =8000
    s.connect((host,port))

    def ts(str,r):
       s.send(r.encode()) 
       data = ''
       data = s.recv(1024).decode()
       print (data)
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    s.close ()
